# Generated by Django 3.1.6 on 2021-02-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(default='d.png', upload_to='frames_pic')),
                ('mask', models.ImageField(default='d.png', upload_to='mask_img')),
            ],
        ),
        migrations.CreateModel(
            name='Merged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_img', models.ImageField(default='d.png', upload_to='merged_pic')),
                ('name', models.CharField(default='', max_length=50)),
                ('village', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Uimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='d.png', upload_to='user_img')),
            ],
        ),
    ]
