# Generated by Django 3.1.6 on 2021-02-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(default='d.png', upload_to='frames_pic')),
            ],
        ),
    ]
