# Generated by Django 3.1.6 on 2021-02-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='orientation',
            field=models.CharField(choices=[('square', 'square'), ('landscape', 'landscape')], default='', max_length=30),
        ),
    ]
