# Generated by Django 3.1.6 on 2021-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_img', models.ImageField(default='d.png', upload_to='merged_pic')),
            ],
        ),
    ]
