# Generated by Django 3.1.6 on 2021-02-16 21:49

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merged'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='mask',
            field=models.ImageField(default='d.png', upload_to='mask_img'),
        ),
        migrations.AlterField(
            model_name='merged',
            name='m_img',
            field=models.ImageField(default='d.png', storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='merged_pic'),
        ),
    ]
