# Generated by Django 3.1.6 on 2021-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_merged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maskimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='d.png', upload_to='mask_img')),
            ],
        ),
    ]
