# Generated by Django 3.1.6 on 2021-02-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210217_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merged',
            name='m_img',
            field=models.ImageField(default='d.png', upload_to='merged_pic'),
        ),
    ]
