# Generated by Django 3.1.6 on 2021-02-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_maskimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maskimg',
        ),
        migrations.AddField(
            model_name='frame',
            name='img',
            field=models.ImageField(default='d.png', upload_to='mask_img'),
        ),
    ]
