# Generated by Django 3.1.6 on 2021-02-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210217_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='merged',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='merged',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='merged',
            name='village',
            field=models.CharField(default='', max_length=50),
        ),
    ]
