# Generated by Django 3.1.6 on 2021-02-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210216_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='img',
            new_name='mask',
        ),
    ]
